---
- hosts: all

  pre_tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      become: true
      tags: [ system ]

  roles:
    - apache