---
# defaults file for mysql
#MySQL Settings
demo_project_mysql_root_password: "mysql_root_password"
demo_project_mysql_db: "wordpress"
demo_project_mysql_user: "sammy"
demo_project_mysql_password: "password"
