---
#System Settings
productstar_php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
productstar_mysql_root_password: "mysql_root_password"
productstar_mysql_db: "wordpress"
productstar_mysql_user: "sammy"
productstar_mysql_password: "password"

#HTTP Settings
productstar_http_host: "your_domain"
productstar_http_conf: "your_domain.conf"
productstar_http_port: "80"