#########################################################
# Wordpress on Ubuntu 22.04 LAMP
#########################################################
---
- hosts: all
  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      become: true
      tags: [ system ]

  roles:
    - role: apache
    - role: mysql
      tags: [molecule-notest]
    - role: php
      tags: [molecule-notest]
    - role: wordpress
      tags: [molecule-notest]
