---
# tasks file for wordpress

# WordPress Configuration

- block:
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/wordpress-{{ lamp_wordpress_version }}.tar.gz
        dest: "/var/www/{{ lamp_wordpress_http_host }}"
        remote_src: yes
        creates: "/var/www/{{ lamp_wordpress_http_host }}/wordpress"
      tags: [ wordpress ]

    - name: Set ownership and permissions for Wordpress files and directories
      file:
        path: "/var/www/{{ lamp_wordpress_http_host }}"
        owner: www-data
        group: www-data
        mode: u=rwX,g=rX,o=rX
        recurse: yes
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "templates/wp-config.php.j2"
        dest: "/var/www/{{ lamp_wordpress_http_host }}/wordpress/wp-config.php"
      tags: [ wordpress ]
  
  become: true