---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    lamp_http_host: "your_domain"
  tasks:
    - name: Ensure the target directory exists
      file:
        path: "/var/www/{{ lamp_http_host }}/wordpress"
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Create index.html with "It works" content
      copy:
        dest: "/var/www/{{ lamp_http_host }}/wordpress/index.html"
        content: "It works"
        owner: root
        group: root
        mode: '0644'
    - name: Verify Apache is serving web requests
      uri:
        url: http://localhost/
        status_code: 200
    - name: Remove the index.html file
      file:
        path: "/var/www/{{ lamp_http_host }}/wordpress/index.html"
        state: absent
